title: K4AHR
lang: en
timezone: Asia/Ho_Chi_Minh

# Author Information
social:
  name: K4AHR
  email: example@example.com
  links:
    - https://github.com/K4AHR

# Blog Settings
paginate: 10
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/

# Markdown and Syntax Highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Excluded Files/Folders
exclude:
  - README.md
  - LICENSE
  - node_modules
  - package*.json
  - tools
  - docs

# Categories and Tags
jekyll-archives:
  enabled: [categories, tags]
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Theme and Plugins
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-toc
  - jemoji
  - jekyll-mentions
